services:
  ms-flights:
    container_name: ms-flights
    labels:
      #- "traefik.backend=ms-flights"
      - "traefik.enable=true"
      - "traefik.http.routers.ms-flights.rule=PathPrefix(`/flights`)"
    user: root # avoids ton of volume mounting headaches in dev mode.
    build:
      context: .
      target: build
    volumes:
      - ./:/opt/app
      # @see: http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html#the-node_modules-volume-trick
      - /opt/app/node_modules
    ports:
      - 5501:5501
    env_file:
      - ./database.env
    depends_on:
      ms-flights-db:
        condition: service_healthy
    environment:
      - NODE_ENV=dev
      - NODE_HOT_RELOAD=1
      - NODE_LOGGER_GRANULARLEVELS=1
      - NODE_CONFIG_DISABLE_FILE_WATCH=Y
    restart: always
    # @see: https://docs.docker.com/compose/startup-order/
    command: ./shell/start-dev.sh

  ms-flights-db:
    container_name: ms-flights-db
    image: mysql:5.7
    ports:
      - 3306
    expose:
      - 3306
    env_file:
      - ./database.env
    volumes:
      - ms_flights_db_vol:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pverysecretsomething"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  ms_flights_db_vol:
